### ISSUE TITLE
Indent line isn't aligned to the collapse button when scrollbar is visible

### ISSUE THREAD

**Issue by zachpoblete** [piroor/tst-indent-line#2]
![image](https://user-images.githubusercontent.com/92368853/188297146-97772203-ba8f-41bb-baf6-8501f85f3cad.png)

**Comment by piroor** [comment]
Which OS? Windows 11 or Ubuntu?

**Comment by KingQuarter** [comment]
Windows 11

**Comment by piroor** [comment]
This should be fixed with recent changes of TST itself and TST Indent Line, but there is a side effect for user styles...

**Comment by zachpoblete** [comment]
Sorry for the late reply, but thanks for the fix!
