### ISSUE TITLE
indet line wont show when the amount of tabs reach the bottom of tst sidebar

### ISSUE THREAD

**Issue by chenjiepeng** [piroor/tst-indent-line#3]
indent line not showing when

**Comment by piroor** [comment]
Could you post any screenshot? I'm using this addon with 100+ tabs but it looks working.

**Comment by piroor** [comment]
One more, could you collect error logs with the debugger console?

You'll see errors happened in the addon via "about:debugging" => "This Firefox" => "Extensions" => "TST Indent Line" => "Inspect" => "Console". More detailed logs are available with "about:addons" => "Extensions" => "TST Indent Line" => "Options" => "Debug mode".

**Comment by chenjiepeng** [comment]
<img width="1231" alt="屏幕截图 2022-09-16 112757" src="https://user-images.githubusercontent.com/17822200/190550754-7a080391-7794-4874-b9b2-a37a982f3032.png">‘

reach the bottom of sidebar ，when scrollbar show and indentline disappear

<img width="1231" alt="屏幕截图 2022-09-16 112839" src="https://user-images.githubusercontent.com/17822200/190550764-9101fdb7-cc14-43de-9c9e-41ec839f9206.png">

**Comment by piroor** [comment]
Thanks, but I still cannot reproduce the problem with deeply nested tree. Hmm...
![image](https://user-images.githubusercontent.com/70062/190551328-9a9ce0bb-bebc-49fe-b578-6bda87350b8c.png)

* Do you use Windows 11? I'm using Windows 10 and it possibly a Windows 11-specific issue.
* Do you use any user stylesheet with TST's options => Advanced?

**Comment by chenjiepeng** [comment]
dont know what does this mean
<img width="1231" alt="屏幕截图 2022-09-16 113939" src="https://user-images.githubusercontent.com/17822200/190551698-98883e74-514c-444c-92bc-418c63aceaa4.png">

**Comment by chenjiepeng** [comment]
> Thanks, but I still cannot reproduce the problem with deeply nested tree. Hmm... ![image](https://user-images.githubusercontent.com/70062/190551328-9a9ce0bb-bebc-49fe-b578-6bda87350b8c.png)
> 
>     * Do you use Windows 11? I'm using Windows 10 and it possibly a Windows 11-specific issue.
> 
>     * Do you use any user stylesheet with TST's options => Advanced?

1. yes it is windows11

<img width="904" alt="屏幕截图 2022-09-16 114328" src="https://user-images.githubusercontent.com/17822200/190552088-7e6fd2b5-26d0-44f8-b6f0-cfc5cb297f42.png">

2. and after i do a firefox refresh this problem still remain，even i reproduce  this on a new installed firefox developer

as i recall，this happened just these several days，probably after the recently Tree Style Tab 3.9.1 and TST Indent Line  1.2 shifted

**Comment by chenjiepeng** [comment]
now i test tst with tst indent line on macos13,it works correctly.

but what is the problem with win11? i have 2000+ tabs opened on that win11 firefox window

could you give me a work around for win11? this is the dubug info

> dont know what does this mean <img alt="屏幕截图 2022-09-16 113939" width="1231" src="https://user-images.githubusercontent.com/17822200/190551698-98883e74-514c-444c-92bc-418c63aceaa4.png">

**Comment by piroor** [comment]
OK I've found the reason why this happens.
Commits cf8d03449ce948bc3c1779e1e30825468bb36c04 and 99d6f12f0ae9c03cc28170a26f85b8c7e6cc1a1f should fix it.

**Comment by piroor** [comment]
I've released v1.2.1 with these changes.
