### ISSUE TITLE
Typo in Extension settings->Options

### ISSUE THREAD

**Issue by wowregistering** [piroor/tst-indent-line#6]
There is a colon after "tab-item" in the example styling when there should not be.
**tab-item:** {
  --indent-line-color: blue;
  --indent-line-color-active: aqua;
}

it should be
**tab-item** {
  --indent-line-color: blue;
  --indent-line-color-active: aqua;
}

**Comment by piroor** [comment]
Thanks! ecf6af1 should fix this.
